export const READ_PHONEBOOK = 'phonebook/read_phonebook'
export const CREATE_PHONEBOOK = 'phonebook/create_phonebook'
export const UPDATE_PHONEBOOK = 'phonebook/update_phonebook'
export const REMOVE_PHONEBOOK = 'phonebook/remove_phonebook'
export const RESEND_PHONEBOOK = 'phonebook/resend_phonebook'
export const SEARCH_PHONEBOOK = 'phonebook/search_phonebook'