export const LOAD_PHONEBOOK = 'LOAD_PHONEBOOK'
export const LOAD_PHONEBOOK_SUCCESS = 'LOAD_PHONEBOOK_SUCCESS'
export const LOAD_PHONEBOOK_FAILURE = 'LOAD_PHONEBOOK_FAILURE'

export const ADD_PHONEBOOK = 'ADD_PHONEBOOK'
export const ADD_DRAW_PHONEBOOK = 'ADD_DRAW_PHONEBOOK'
export const ADD_PHONEBOOK_SUCCESS = 'ADD_PHONEBOOK_SUCCESS'
export const ADD_PHONEBOOK_FAILURE = 'ADD_PHONEBOOK_FAILURE'

export const REMOVE_PHONEBOOK = 'REMOVE_PHONEBOOK'
export const REMOVE_DRAW_PHONEBOOK = 'REMOVE_DRAW_PHONEBOOK'
export const REMOVE_PHONEBOOK_SUCCESS = 'REMOVE_PHONEBOOK_SUCCESS'
export const REMOVE_PHONEBOOK_FAILURE = 'REMOVE_PHONEBOOK_FAILURE'